<?php

// autoload_static.php @generated by Composer

namespace Composer\Autoload;

class ComposerStaticInit9cb3d0c993a094f227e0d2f0ce1ee257
{
    public static $prefixLengthsPsr4 = array (
        'D' => 
        array (
            'DLXPlugins\\InstaAdmin\\' => 22,
        ),
    );

    public static $prefixDirsPsr4 = array (
        'DLXPlugins\\InstaAdmin\\' => 
        array (
            0 => __DIR__ . '/../..' . '/php',
        ),
    );

    public static $classMap = array (
        'Composer\\InstalledVersions' => __DIR__ . '/..' . '/composer/InstalledVersions.php',
    );

    public static function getInitializer(ClassLoader $loader)
    {
        return \Closure::bind(function () use ($loader) {
            $loader->prefixLengthsPsr4 = ComposerStaticInit9cb3d0c993a094f227e0d2f0ce1ee257::$prefixLengthsPsr4;
            $loader->prefixDirsPsr4 = ComposerStaticInit9cb3d0c993a094f227e0d2f0ce1ee257::$prefixDirsPsr4;
            $loader->classMap = ComposerStaticInit9cb3d0c993a094f227e0d2f0ce1ee257::$classMap;

        }, null, ClassLoader::class);
    }
}
